"""Add models table and update devices

Revision ID: aab7a0cb0df1
Revises: 8d0d28ab528a
Create Date: 2025-08-05 10:57:50.418366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab7a0cb0df1'
down_revision: Union[str, None] = '8d0d28ab528a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('oid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'models', ['model_id'], ['id'])
    op.drop_column('devices', 'oid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('oid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'model_id')
    op.drop_table('models')
    # ### end Alembic commands ###
